"use client";

import { useState } from "react";
import { ActionMenu } from "./ActionMenu";
import { IconCheck, IconDownload, IconLink, IconPrint } from "./Icons";
import type { PdfLink } from "@/lib/pdf";

// Download is the primary action; the menu holds the rest. For a document
// written on the site the PDF is printed from this same page, so the two
// cannot differ, and under `next dev` before a ship run the primary action
// opens the print view instead (see lib/pdf.ts). For a delivered document
// the PDF is the document itself: the viewer beside this is the primary
// action, download goes quiet, and there is no print view to offer.
export function PdfMenu({ link, file, printHref, title, upload = false }: { link: PdfLink; file: string; printHref: string; title: string; upload?: boolean }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {}
  };
  const items = [
    ...(upload ? [] : [{ label: "Open print view", icon: <IconPrint />, href: printHref, external: true }]),
    { label: copied ? "Link copied" : "Copy link to this page", icon: copied ? <IconCheck /> : <IconLink />, onSelect: copy }
  ];
  return (
    <div className="flex items-center gap-2 no-print">
      {link.file ? (
        <a className={`btn ${upload ? "btn-ghost" : "btn-primary"}`} href={link.href} download={file} title={`Download ${title} as PDF`}>
          <IconDownload />
          Download PDF
        </a>
      ) : (
        <a className="btn btn-primary" href={link.href} target="_blank" rel="noopener" title="The PDF is generated by npm run ship; this opens the print view it is made from">
          <IconPrint />
          Print view
        </a>
      )}
      <ActionMenu label="More" align="right" items={items} />
    </div>
  );
}
