"use client";

import { useState } from "react";
import { ActionMenu } from "./ActionMenu";
import { IconCheck, IconDownload, IconLink, IconPrint } from "./Icons";
import type { PdfLink } from "@/lib/pdf";

// Download is the primary action; the menu holds the rest. The PDF is
// generated from the same source as this page, so the two cannot differ.
// Under `next dev` before a ship run there is no PDF yet, and the primary
// action opens the print view instead (see lib/pdf.ts).
export function PdfMenu({ link, file, printHref, title }: { link: PdfLink; file: string; printHref: string; title: string }) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    } catch {}
  };
  return (
    <div className="flex items-center gap-2 no-print">
      {link.file ? (
        <a className="btn btn-primary" href={link.href} download={file} title={`Download ${title} as PDF`}>
          <IconDownload />
          Download PDF
        </a>
      ) : (
        <a className="btn btn-primary" href={link.href} target="_blank" rel="noopener" title="The PDF is generated by npm run ship; this opens the print view it is made from">
          <IconPrint />
          Print view
        </a>
      )}
      <ActionMenu
        label="More"
        align="right"
        items={[
          { label: "Open print view", icon: <IconPrint />, href: printHref, external: true },
          { label: copied ? "Link copied" : "Copy link to this page", icon: copied ? <IconCheck /> : <IconLink />, onSelect: copy }
        ]}
      />
    </div>
  );
}
