import { existsSync } from "node:fs";
import { join } from "node:path";
import { withBase } from "./base";
import type { PortalDocument } from "./registry";

// Where a document's PDF button points. The PDFs are printed from the pages
// by `npm run ship`, after the build, so on the published site the file is
// always there. Under `next dev` it is there only once ship has run (the
// script leaves a copy in public/pdf/ for the dev server); until then the
// button opens the print view the PDF is made from, so it still leads
// somewhere instead of saving a 404 page. Server components only: it reads
// the filesystem.
export interface PdfLink {
  href: string;
  /** True when the link is the PDF itself and should download. */
  file: boolean;
}

export function pdfLink(doc: Pick<PortalDocument, "pdf" | "source" | "file">, printHref: string): PdfLink {
  // A delivered document is its own file, committed under public/docs/.
  if (doc.source === "upload" && doc.file) return { href: withBase(`/docs/${doc.file}`), file: true };
  const href = withBase(`/pdf/${doc.pdf}.pdf`);
  if (process.env.NODE_ENV !== "development") return { href, file: true };
  const built = existsSync(join(process.cwd(), "public", "pdf", `${doc.pdf}.pdf`));
  return built ? { href, file: true } : { href: printHref, file: false };
}

export const pdfTitle = (link: PdfLink, title: string) =>
  link.file ? `Download ${title} as PDF` : `The PDF is generated by npm run ship; this opens the print view it is made from`;
