// Generates app/accents.css from content/accents.json so the picker, the
// contrast check and the stylesheet all read one source. Runs before build
// and dev; the output is committed as well so a fresh clone works without it.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spec = JSON.parse(readFileSync(join(root, "content/accents.json"), "utf8"));

const block = (sel, t) => `${sel} {
  --accent: ${t.accent};
  --accent-hover: ${t.hover};
  --accent-soft: ${t.soft};
  --accent-ink: ${t.ink};
  --on-accent: ${t.on};
}`;

let css = `/* Generated by scripts/accents-css.mjs from content/accents.json. Do not edit. */\n`;
css += `:root { --paper-base: ${spec.paper.light}; --tint: ${spec.tint}%; }\n`;
css += `:root[data-theme="dark"] { --paper-base: ${spec.paper.dark}; }\n\n`;
for (const acc of spec.accents) {
  const isDefault = acc.id === spec.default;
  const light = isDefault ? `:root, :root[data-accent="${acc.id}"]` : `:root[data-accent="${acc.id}"]`;
  const dark = isDefault
    ? `:root[data-theme="dark"], :root[data-theme="dark"][data-accent="${acc.id}"]`
    : `:root[data-theme="dark"][data-accent="${acc.id}"]`;
  css += block(light, acc.light) + "\n" + block(dark, acc.dark) + "\n\n";
}
writeFileSync(join(root, "app/accents.css"), css);
console.log(`app/accents.css written (${spec.accents.length} presets, default ${spec.default}).`);
