// Generates app/accents.css from content/accents.json so the picker, the
// contrast check and the stylesheet all read one source. Each preset is a
// whole palette, neutrals included, in a light and a dark version; the
// default one also applies on bare :root so a visitor who never picks gets
// it. Runs before build and dev; the output is committed as well so a fresh
// clone works without it.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const spec = JSON.parse(readFileSync(join(root, "content/accents.json"), "utf8"));

const TOKENS = {
  paper: "--paper",
  surface: "--surface",
  surfaceSubtle: "--surface-subtle",
  surfaceMuted: "--surface-muted",
  ink: "--ink",
  inkSoft: "--ink-soft",
  labelInk: "--label-ink",
  muted: "--muted",
  border: "--border",
  hoverBorder: "--hover-border",
  railBg: "--rail-bg",
  railText: "--rail-text",
  accent: "--accent",
  hover: "--accent-hover",
  soft: "--accent-soft",
  accentInk: "--accent-ink",
  on: "--on-accent"
};

const block = (sel, t) => {
  const lines = Object.entries(TOKENS).map(([key, name]) => {
    if (!t[key]) throw new Error(`palette is missing "${key}"`);
    return `  ${name}: ${t[key]};`;
  });
  return `${sel} {\n${lines.join("\n")}\n}`;
};

let css = `/* Generated by scripts/accents-css.mjs from content/accents.json. Do not edit. */\n\n`;
for (const acc of spec.accents) {
  const isDefault = acc.id === spec.default;
  const light = isDefault ? `:root, :root[data-accent="${acc.id}"]` : `:root[data-accent="${acc.id}"]`;
  const dark = isDefault
    ? `:root[data-theme="dark"], :root[data-theme="dark"][data-accent="${acc.id}"]`
    : `:root[data-theme="dark"][data-accent="${acc.id}"]`;
  css += block(light, acc.light) + "\n" + block(dark, acc.dark) + "\n\n";
}
writeFileSync(join(root, "app/accents.css"), css);
console.log(`app/accents.css written (${spec.accents.length} palettes, default ${spec.default}).`);
